### ISSUE TITLE
Whats the optimal order to run pihole scripts in?

### ISSUE THREAD

**Issue by Tokogon** [mmotti/pihole-gravity-optimise#11]
Howdy!

Happy user here confused about the example cron job times. Should gravity-optimise always be run last and does it matter what order I run  filter-lists and gravity-wildcards in?

**Comment by mmotti** [comment]
Hi!

This is a very good question and perhaps something that I have overlooked in terms of providing sample cron times.

So, essentially the optimal way to run things is in the following order:

1. `pihole -g`
2. gravity wildcards
3. filter lists
4. gravity optimise

The reason for this is that you want to re-populate gravity in order to generate the wildcards that will be effective for your setup. Then, you want to download the additional wildcards using filter lists and finally remove unnecessary domains with gravity optimise.

I hope this helps!

**Comment by Tokogon** [comment]
Thanks!
