### ISSUE TITLE
Getting syntax error with new script

### ISSUE THREAD

**Issue by DannyBeanz** [mmotti/pihole-gravity-optimise#13]
Hi,

I've followed the updated instructions for the optimise script and now receive the following error:
```
pi@raspberrypi:~ $ sudo curl -sSl https://raw.githubusercontent.com/mmotti/pihole-gravity-optimise/master/gravityOptimise.py | sudo python3
  File "<stdin>", line 52                                                                                                                 
    print(f'{path_pihole} was not found')                                                                                                 
                                       ^
SyntaxError: invalid syntax
```

I've tried this as the 'pi' user, using 'sudo', and also as a root user.

Any suggestions?  I have a feeling it will be something really obvious....

**Comment by mmotti** [comment]
It's not too obvious this one - Perhaps something I need to add to the main readme.

This has occurred for people on my other script for pihole regex too: https://github.com/mmotti/pihole-regex/issues/16

Take a look through :-) it's essentially because you need Python 3.6+ and older versions of Raspbian etc haven't got the most up-to-date Python packages. That link should provide a workaround though.

**Comment by DannyBeanz** [comment]
Thanks for that, reading now.
