### ISSUE TITLE
Grep

### ISSUE THREAD

**Issue by MarkDarwin** [mmotti/pihole-gravity-optimise#14]
Just found your code and have been trying it out but running into the error below about grep:

> [i] Root user detected
[i] Pi-hole path exists
[i] Updating gravity (this may take a little time)
[i] Legacy lists detected
[i] Fetching domains
[i] --> 161799 domains found
[i] Scanning /etc/dnsmasq.d for wildcards
[i] --> 29793 wildcards found
[i] Identifying wildcard conflicts with gravity
[i] --> 46554 conflicts found
[i] Fetching regexps
[i] --> 39 regexps found
[i] Checking for gravity matches
[i] --> **_An error occurred when running grep command_**
[i] Outputting updated gravity.list
[i] --> 87784 domains remain in gravity.list
[i] Restarting Pi-hole

It looks like it's doing at least part of the process as the blocked domains is reduced but I'm not sure how to troubleshoot why it's breaking down around I think liine 219 and             `grep_result = [x for x in cmd.communicate()[0].split('\n') if x]`

If it helps, my settings are:

**Regex:**
> ^telemetry[-.]
> (^|\.)glock\.com$
> (^|\.)ad\.youtube\.com$
> (^|\.)innovid\.com$
> (^|\.)ads\.youtube\.com$
> (^|\.)anno\.channel4\.com$
> (^|\.)pagead2\.googlesyndication\.com$
> (^|\.)Dailymail\.(com|co.uk)
> (^|\.)tubemogul\.com$
> (^|\.)2mdn\.net$
> (^|\.)adform\.net$
> (^|\.)analytic-google\.com$
> (^|\.)News\.sky\.com$
> (^|\.)skysports\.com$
> ^adse?rv(e(rs?)?|ices?)?[0-9]*[-.]
> ^adtrack(er|ing)?[0-9]*[-.]
> ^analytics?[-.]
> ^pixels?[-.]
> ^stat(s|istics)?[0-9]*[-.]
> ^track(ers?|ing)?[0-9]*[-.]
> (^r[[:digit:]]+(\.|\-+)[[:alnum:]]+\-+[[:alnum:]]+\-+[[:alnum:]]+\.)(googlevideo|gvt1)\.com$
> (^r[[:digit:]]+(\-+|\.+)[a-z]+\-+[[:alnum:]]+\-+[[:alnum:]]+\.)(googlevideo|gvt1)\.com$
> (^r[[:digit:]]+(-+|.+)[a-z]+-+[[:alnum:]]+-+[[:alnum:]]+.)(googlevideo|gvt1).com$
> ^[a-z0-9]{16}\.[a-z0-9]{6,10}\.(bid|top|kim|lol|pro|win|link|pl|at|loan|pw|red|gdn|li)
> (^|\.)online-metrix\.net$
> (^|\.)we-stats\.com$
> (^|\.)appdynamics\.com$
> ^.*(usage|sec|collect).*(myhomescreen.tv)
> (^|\.leanplum.com$
> (^|\.)aaxads.com$
> (^|\.)jwpsrv\.com$
> bannertrack.net
> ^ad(|vert)(s|is(ing|ements?))?[0-9]*[-_.]
> ^banner(s?)[0-9]*[-_.]
> ^traff(ic)?[-.]
> .*\.g[0-9]+\..*
> ^mads\.
> ^adim(age|g)s?[0-9]*[_.-]
> ([A-Za-z0-9.-]*\.)?doubleclick(\.\w{2}\.\w{2}|\.\w{2,4})
> 

**Blacklist**

> collect-eu-fy2015.myhomescreen.tv
> usage-eu-fy2015.myhomescreen.tv
> r4---sn-aigzrn7e.googlevideo.com
> adjust.com
> 

**Blocklist:**

> https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts 	
> https://mirror1.malwaredomains.com/files/justdomains 	
> http://sysctl.org/cameleon/hosts 	
> https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist 	
> https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt 	
> https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt 	
> https://hosts-file.net/ad_servers.txt 	
> https://v.firebog.net/hosts/AdguardDNS.txt 	
> https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
> 

Super cool piece of code though, just wish I understood it more!

**Comment by mmotti** [comment]
Thanks for providing such detail regarding your issue.

I'm away from home for a couple of days, but will look when I can.

Essentially the script at that point checks the grep return code. 0 if
lines are found, 1 if no matches are found and 2 if an error has occurred
when trying to run the command.

If I were to guess, I would say that one or more of your regexps could be
invalid, or not the right flavour of regex for grep extended expressions.
The easiest way to troubleshoot this would be to try removing all those
that aren't standard wildcards, or entries from my regex list. That's how I
would personally start to troubleshoot.

**Comment by mmotti** [comment]
Also try updating to the latest version of this script. I can see by the lack of comma separators on the domain count printout that it isn't the latest version :-)

**Comment by MarkDarwin** [comment]
Thanks for the super quick reply.
Can confirm to test I sudo su'd then ran:
`curl -sSl https://raw.githubusercontent.com/mmotti/pihole-gravity-optimise/master/gravityOptimise.py | sudo python3`
So it should be the latest version of the code I think?

Will check through the regex's tail end of the week and see which ones I have wrong.

**Comment by mmotti** [comment]
Ah, okay... That should pull the correct version. It looks to be still
using an older version though as there most definitely should be comma
separators on the numerical output of domains etc (although this would
still not likely solve your particular error). I remember tweaking it; you
should see this on the example output in the readme.

There is a switch for the curl command to tell it not to use cache,
assuming it might have cached an older copy. I will perhaps look at
adapting the command when I'm able to get to my laptop to prevent possible
future confusion.

Identifying the problematic regexps should be the fix in your case though.
If you don't get a chance to look into this before I'm back at my laptop, I
shall also have a look

Edit: Actually this could even be a locale issue (for comma separators), rather than not being the latest script. But it might be worth trying with a fresh cache copy anyway

**Comment by mmotti** [comment]
So I would guess your immediate issue is as follows:

```
(^|.leanplum.com$
grep: Unmatched ( or \(
```
Also, if you are going to use this kind of regexp to define a wildcard, it doesn't currently work as you think it does.

The correct syntax for your wildcards in the way that you've currently got them would be: `(^|\.)test\.com`

Note the escaped `.` - Otherwise you are saying at the **start of the string** or **after any character**, **test**, **any character**, **com**

Also things like `^ad(|vert)(s|is(ing|ements?))?[0-9][-_.]` - **(|vert)** you are using an OR statement here and a capture group for no reason as you only include **vert** and no other option.

I would start from the ground up with your regexps and make sure they're all doing what you intend them to :-) It's a tricky business but once you start to wrap your head around them, they start to make sense.

However, short term, I would guess that if you were to correct the grep error above the script would probably run as you expect.

**Comment by MarkDarwin** [comment]
Thanks so much for the help, and apologies for wasting your time.
I had read that pihole uses some different variant of regex but have not been able to find a way to test.  Looking at your code it seems I can run `grep '(^|\.)test\.com' gravityfile` and if it matches then theres a url in there somewhere.  That gets me to where I can check which is really useful that I didn't know I could do.

I took one of your regex's and can get a visual for how it works [here ](https://regexper.com/#%5E%28.%2B%5B_.-%5D%29%3Fadse%3Frv%28er%3F%7Cice%29%3Fs%3F%5B0-9%5D*%5B_.-%5D%0A)which should help me learn too.

Again, thanks very much for taking the time to explain things, it's really appreciated.

**Comment by mmotti** [comment]
No problem. I believe you need to use the `-E` flag for it to be more representative to the regexp matching that pihole does (I.e `grep -E`) 

Also after you've updated to pihole v5 the testing with grep will not be possible against the gravity list as the data is migrated to a database. But for now, getting a feel for it, will be fine.
