### ISSUE TITLE
Cannot allocate memory - Again

### ISSUE THREAD

**Issue by GokulG07** [mmotti/pihole-gravity-optimise#16]
Please look into it. And also the Blacklist is the same as before which i gave you!

> pi@raspberrypi:~ $ curl -sSl https://raw.githubusercontent.com/mmotti/pihole-gravity-optimise/master/gravityOptimise.py | sudo python3
[i] Root user detected
[i] Pi-hole path exists
[i] Updating gravity (this may take a little time)
[i] Legacy lists detected
[i] Fetching domains
[i] --> 5,023,970 domains found
[i] Scanning /etc/dnsmasq.d for wildcards
[i] --> 36,683 wildcards found
[i] Identifying wildcard conflicts with gravity
[i] --> 242,829 conflicts found
[i] Fetching regexps
[i] --> 18 regexps found
[i] Checking for gravity matches
Traceback (most recent call last):
  File "<stdin>", line 217, in <module>
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory

**Comment by mmotti** [comment]
I'm not sure that it's worth trying to implement changes in the script to resolve this as it would require quite a re-write to split the grep into smaller chunks to try save some memory during processing.

The reason why I don't think it's a great idea to spend time adapting this is because as of pihole v5, this script will serve little benefit. One of the pros for using it with older versions of pihole was that it could significantly reduce the size of gravity.list (disk space) but when removing items from the database in v5, you don't gain any space back unless you also get the DB to rebuild itself after each run and it's just not worthwhile.

That and the fact that any changes are effectively undone by any gravity run and there's not really a great way to inject it into piholes gravity process without making the local repo dirty and potentially causing issues with pihole updates.

For this to work properly, it or a similar method would need to be injected into piholes gravity script (or officially implemented) but I don't think the Devs see much benefit as the lookups aren't affected too much and it's just extra processing time and resources added to gravity

**Comment by GokulG07** [comment]
Okay its fine with me.....Thanks for the support
