### ISSUE TITLE
Blocklist shows 0 domains

### ISSUE THREAD

**Issue by ajp2k13** [mmotti/pihole-gravity-optimise#2]
After running gravityOptimise.sh my blocklist shows 0 domains. If i check /etc/pihole/gravity.list it's all there and the blocking seems to work. It didn't use to be like this, happened after I updated the script.

**Comment by mmotti** [comment]
Thanks for reporting this.

Please could you:
1. Copy / paste the output of the script into here
2. Confirm what version of Pi-hole you are using - Standard or have you checked out the DEV branch?

**Comment by ajp2k13** [comment]
[i] Updating gravity.list
[i] Parsing existing wildcard config (DNSMASQ)
[i] Removing wildcard matches in gravity.list
[i] Removing regex.list matches
[i] Updating gravity database
[i] Removing temp files
[i] Sending SIGHUP to Pihole
[i] 46563 domains were removed from gravity
[i] 66871 domains remain in gravity

  Pi-hole version is v4.3 (Latest: v4.3)
  AdminLTE version is v4.3 (Latest: v4.3)
  FTL version is v4.3.1 (Latest: v4.3.1)

Running Raspbian Stretch on a Pi 3B+

Thanks!

**Comment by mmotti** [comment]
Thanks :-)

So it can see that you are using the old gravity.list and not the new DB which is encouraging.

I think the issue here is that I had implemented a new behaviour to save to a temp file, then `mv` this over `/etc/pihole/gravity.list` but then the permissions are wrong.

Could you try run the following commands?
```
sudo chmod 0644 /etc/pihole/gravity.list
sudo chown root /etc/pihole/gravity.list
sudo chgrp root /etc/pihole/gravity.list
sudo service pihole-FTL restart
```
I'll update the script to simply overwrite the existing file instead of replacing with the temporary file.

**Comment by ajp2k13** [comment]
Yes, now it shows the correct amount of blocked domains! 👍

**Comment by mmotti** [comment]
Excellent :-)

The script has been updated to use `cp` instead of `mv` which preserves the permissions of the original file.

**Comment by ajp2k13** [comment]
Excellent! Thanks for the help... :)
